function out1 = Modell3_dfdx_10p(in1,in2,DOTstern)
%Modell3_dfdx_10p
%    OUT1 = Modell3_dfdx_10p(IN1,IN2,DOTstern)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    08-Aug-2026 11:05:36

KAm = in2(9,:);
KLa = in2(7,:);
KPh = in2(10,:);
KS = in2(2,:);
V = in1(1,:);
YAmX = in2(4,:);
YB_Am = in2(6,:);
YPhX = in2(5,:);
YXO = in2(8,:);
YXS = in2(3,:);
mAm = in1(4,:);
mGlc = in1(3,:);
mPh = in1(5,:);
mX = in1(2,:);
mumax = in2(1,:);
t2 = mAm.^2;
t3 = mGlc.^2;
t4 = mPh.^2;
t5 = 1.0./V;
t10 = 1.0./YXO;
t11 = 1.0./YXS;
t6 = t5.^3;
t7 = t5.^4;
t8 = t5.^5;
t12 = mAm.*t5;
t13 = mGlc.*t5;
t14 = mPh.*t5;
t9 = t6.^2;
t15 = KAm+t12;
t16 = KS+t13;
t17 = KPh+t14;
t18 = 1.0./t15;
t20 = 1.0./t16;
t22 = 1.0./t17;
t19 = t18.^2;
t21 = t20.^2;
t23 = t22.^2;
mt1 = [0.0,mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t22.*-3.0+mAm.*mGlc.*mX.*mumax.*t4.*t8.*t18.*t20.*t23+mAm.*mPh.*mX.*mumax.*t3.*t8.*t18.*t21.*t22+mGlc.*mPh.*mX.*mumax.*t2.*t8.*t19.*t20.*t22,mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t11.*t18.*t20.*t22.*3.0-mAm.*mGlc.*mX.*mumax.*t4.*t8.*t11.*t18.*t20.*t23-mAm.*mPh.*mX.*mumax.*t3.*t8.*t11.*t18.*t21.*t22-mGlc.*mPh.*mX.*mumax.*t2.*t8.*t11.*t19.*t20.*t22,YAmX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t22.*3.0-YAmX.*mAm.*mGlc.*mX.*mumax.*t4.*t8.*t18.*t20.*t23-YAmX.*mAm.*mPh.*mX.*mumax.*t3.*t8.*t18.*t21.*t22-YAmX.*mGlc.*mPh.*mX.*mumax.*t2.*t8.*t19.*t20.*t22,YPhX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t22.*3.0-YPhX.*mAm.*mGlc.*mX.*mumax.*t4.*t8.*t18.*t20.*t23-YPhX.*mAm.*mPh.*mX.*mumax.*t3.*t8.*t18.*t21.*t22-YPhX.*mGlc.*mPh.*mX.*mumax.*t2.*t8.*t19.*t20.*t22];
mt2 = [YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t22.*-3.0+YAmX.*YB_Am.*mAm.*mGlc.*mX.*mumax.*t4.*t8.*t18.*t20.*t23+YAmX.*YB_Am.*mAm.*mPh.*mX.*mumax.*t3.*t8.*t18.*t21.*t22+YAmX.*YB_Am.*mGlc.*mPh.*mX.*mumax.*t2.*t8.*t19.*t20.*t22];
mt3 = [mAm.*mGlc.*mPh.*mX.*mumax.*t8.*t10.*t18.*t20.*t22.*5.602240896358544e+4-mAm.*mGlc.*mX.*mumax.*t4.*t9.*t10.*t18.*t20.*t23.*1.400560224089636e+4-mAm.*mPh.*mX.*mumax.*t3.*t9.*t10.*t18.*t21.*t22.*1.400560224089636e+4-mGlc.*mPh.*mX.*mumax.*t2.*t9.*t10.*t19.*t20.*t22.*1.400560224089636e+4,0.0,mAm.*mGlc.*mPh.*mumax.*t6.*t18.*t20.*t22,-mAm.*mGlc.*mPh.*mumax.*t6.*t11.*t18.*t20.*t22];
mt4 = [-YAmX.*mAm.*mGlc.*mPh.*mumax.*t6.*t18.*t20.*t22,-YPhX.*mAm.*mGlc.*mPh.*mumax.*t6.*t18.*t20.*t22,YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mumax.*t6.*t18.*t20.*t22,mAm.*mGlc.*mPh.*mumax.*t7.*t10.*t18.*t20.*t22.*(-1.400560224089636e+4),0.0,mAm.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22-mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t21.*t22,-mAm.*mPh.*mX.*mumax.*t6.*t11.*t18.*t20.*t22+mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t11.*t18.*t21.*t22,-YAmX.*mAm.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22+YAmX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t21.*t22,-YPhX.*mAm.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22+YPhX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t21.*t22,YAmX.*YB_Am.*mAm.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22-YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t21.*t22];
mt5 = [mAm.*mPh.*mX.*mumax.*t7.*t10.*t18.*t20.*t22.*(-1.400560224089636e+4)+mAm.*mGlc.*mPh.*mX.*mumax.*t8.*t10.*t18.*t21.*t22.*1.400560224089636e+4,0.0,mGlc.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22-mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t19.*t20.*t22,-mGlc.*mPh.*mX.*mumax.*t6.*t11.*t18.*t20.*t22+mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t11.*t19.*t20.*t22,-YAmX.*mGlc.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22+YAmX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t19.*t20.*t22,-YPhX.*mGlc.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22+YPhX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t19.*t20.*t22];
mt6 = [YAmX.*YB_Am.*mGlc.*mPh.*mX.*mumax.*t6.*t18.*t20.*t22-YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t19.*t20.*t22,mGlc.*mPh.*mX.*mumax.*t7.*t10.*t18.*t20.*t22.*(-1.400560224089636e+4)+mAm.*mGlc.*mPh.*mX.*mumax.*t8.*t10.*t19.*t20.*t22.*1.400560224089636e+4,0.0,mAm.*mGlc.*mX.*mumax.*t6.*t18.*t20.*t22-mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t23,-mAm.*mGlc.*mX.*mumax.*t6.*t11.*t18.*t20.*t22+mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t11.*t18.*t20.*t23,-YAmX.*mAm.*mGlc.*mX.*mumax.*t6.*t18.*t20.*t22+YAmX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t23];
mt7 = [-YPhX.*mAm.*mGlc.*mX.*mumax.*t6.*t18.*t20.*t22+YPhX.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t23,YAmX.*YB_Am.*mAm.*mGlc.*mX.*mumax.*t6.*t18.*t20.*t22-YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*mumax.*t7.*t18.*t20.*t23,mAm.*mGlc.*mX.*mumax.*t7.*t10.*t18.*t20.*t22.*(-1.400560224089636e+4)+mAm.*mGlc.*mPh.*mX.*mumax.*t8.*t10.*t18.*t20.*t23.*1.400560224089636e+4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-KLa];
out1 = reshape([mt1,mt2,mt3,mt4,mt5,mt6,mt7],7,7);
end
