function out1 = Modell3_dfdp_10p(in1,in2,DOTstern)
%Modell3_dfdp_10p
%    OUT1 = Modell3_dfdp_10p(IN1,IN2,DOTstern)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    08-Aug-2026 11:05:37

DOT = in1(7,:);
KAm = in2(9,:);
KPh = in2(10,:);
KS = in2(2,:);
V = in1(1,:);
YAmX = in2(4,:);
YB_Am = in2(6,:);
YPhX = in2(5,:);
YXO = in2(8,:);
YXS = in2(3,:);
mAm = in1(4,:);
mGlc = in1(3,:);
mPh = in1(5,:);
mX = in1(2,:);
mumax = in2(1,:);
t2 = 1.0./V;
t5 = 1.0./YXO;
t6 = 1.0./YXS;
t3 = t2.^3;
t4 = t2.^4;
t7 = mAm.*t2;
t8 = mGlc.*t2;
t9 = mPh.*t2;
t10 = KAm+t7;
t11 = KS+t8;
t12 = KPh+t9;
t13 = 1.0./t10;
t15 = 1.0./t11;
t17 = 1.0./t12;
t14 = t13.^2;
t16 = t15.^2;
t18 = t17.^2;
t19 = mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t15.*t17;
t20 = -t19;
mt1 = [0.0,mAm.*mGlc.*mPh.*mX.*t3.*t13.*t15.*t17,-mAm.*mGlc.*mPh.*mX.*t3.*t6.*t13.*t15.*t17,-YAmX.*mAm.*mGlc.*mPh.*mX.*t3.*t13.*t15.*t17,-YPhX.*mAm.*mGlc.*mPh.*mX.*t3.*t13.*t15.*t17,YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*t3.*t13.*t15.*t17,mAm.*mGlc.*mPh.*mX.*t4.*t5.*t13.*t15.*t17.*(-1.400560224089636e+4),0.0,-mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t16.*t17,mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t6.*t13.*t16.*t17,YAmX.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t16.*t17,YPhX.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t16.*t17,-YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t16.*t17,mAm.*mGlc.*mPh.*mX.*mumax.*t4.*t5.*t13.*t16.*t17.*1.400560224089636e+4,0.0];
mt2 = [0.0,t6.^2.*t19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t20,0.0,YB_Am.*t19,0.0,0.0,0.0,0.0,0.0,t20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,YAmX.*t19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-DOT+DOTstern,0.0,0.0,0.0,0.0,0.0,0.0,mAm.*mGlc.*mPh.*mX.*mumax.*t4.*t5.^2.*t13.*t15.*t17.*1.400560224089636e+4,0.0,-mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t14.*t15.*t17,mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t6.*t14.*t15.*t17,YAmX.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t14.*t15.*t17,YPhX.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t14.*t15.*t17,-YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t14.*t15.*t17,mAm.*mGlc.*mPh.*mX.*mumax.*t4.*t5.*t14.*t15.*t17.*1.400560224089636e+4,0.0];
mt3 = [-mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t15.*t18,mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t6.*t13.*t15.*t18,YAmX.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t15.*t18,YPhX.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t15.*t18,-YAmX.*YB_Am.*mAm.*mGlc.*mPh.*mX.*mumax.*t3.*t13.*t15.*t18,mAm.*mGlc.*mPh.*mX.*mumax.*t4.*t5.*t13.*t15.*t18.*1.400560224089636e+4];
out1 = reshape([mt1,mt2,mt3],7,10);
end
